blank_issues_enabled: false
contact_links:
  - name: Dúvidas gerais da disciplina
    url: https://github.com/orgs/ELT85B-N21-2026-2/discussions
    about: Para dúvidas que não sejam sobre inclusão em times, use as Discussions da organização.
    